{% set name = "PANKEGG" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RVanDamme/PANKEGG/archive/{{ version }}.tar.gz
  sha256: 0517c71ea9116ed71211a05570cf6fdef47b4446099b51e90ba6557bce1451cb

build:
  number: 0
  # script:
  #   - cp -r $SRC_DIR $SP_DIR/PANKEGG
  #   - ls $SRC_DIR/PANKEGG/parser.py 
requirements:
  build:
    - python  3.8

  run:
    - python  3.8

test:
  imports:
    - PANKEGG

  commands:
    - pankegg-v > /dev/null
app:
  entry: PANKEGG/parser.py

about:
  home: https://github.com/RVanDamme/PANKEGG/
  license_file: LICENSE
  summary: 'Parsing eggnog annotation file and quantitication file from trinity'
  description: |
    This script is part of the MAFIN pipeline and parse the annotations files from eggnog
    as well as the quantification of the RNA reads mapped to the transcript to output
    nice html result files
  dev_url: https://github.com/RVanDamme/PANKEGG/
  doc_source_url: https://github.com/RVanDamme/PANKEGG/blob/master/README.md