{% set name = "PANKEGG" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RVanDamme/PANKEGG/archive/{{ version }}.tar.gz
  sha256: 4784b3c6ad064d8cb097b6cccc6782a3b3ac256b407dd9f37d1c31e934a77285

build:
  number: 0
  script: cp -r $SRC_DIR/PANKEGG $SP_DIR/PANKEGG;
    python $SRC_DIR/setup.py install --single-version-externally-managed --record=record.txt;
    cp $SRC_DIR/bin/pankegg $PREFIX/bin/pankegg # [not win]
  link: bin/pankegg

requirements:
  build:
    - python  3.8

  run:
    - python  3.8

test:
  imports:
    - PANKEGG

  commands:
    #- pankegg -v > /dev/null
app:
  entry: pankegg

about:
  home: https://github.com/RVanDamme/PANKEGG/
  license_file: LICENSE
  summary: 'Parsing eggnog annotation file and quantitication file from trinity'
  description: |
    This script is part of the MAFIN pipeline and parse the annotations files from eggnog
    as well as the quantification of the RNA reads mapped to the transcript to output
    nice html result files
  dev_url: https://github.com/RVanDamme/PANKEGG/
  doc_source_url: https://github.com/RVanDamme/PANKEGG/blob/master/README.md
