package:
  name: "pankegg"
  version: "0.1.0"

source:
  git_url: https://github.com/RVanDamme/PANKEGG.git
  git_rev: 0.1.0
  git_depth: 1

requirements:
  build:
    - python  3.8

  run:
    - python  3.8

# test:
  # imports:
  #   - #

  # commands:
  #   - PANKEGG/parser.py -v > /dev/null

about:
  home: https://github.com/RVanDamme/PANKEGG/
  license: LICENSE
  summary: 'Parsing eggnog annotation file and quantitication file from trinity'
  description: |
    This script is part of the MAFIN pipeline and parse the annotations files from eggnog
    as well as the quantification of the RNA reads mapped to the transcript to output
    nice html result files
  dev_url: https://github.com/RVanDamme/PANKEGG/
  doc_source_url: https://github.com/RVanDamme/PANKEGG/blob/master/README.md