{% set name = "PANKEGG" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RVanDamme/PANKEGG/archive/{{ version }}.tar.gz
  sha256: 6dd32b274644739bebd49fd5ca8395fed8122ef186f51f1d5ea8a6e8c43b4a8f

build:
  number: 0
  script: cp -r $SRC_DIR/PANKEGG $SP_DIR/PANKEGG; # [not win]
  # link: bin/pankegg

requirements:
  build:
    - python  3.8

  run:
    - python  3.8

test:
  imports:
    - PANKEGG

  # commands:

# app:
#   entry: parser.py

about:
  home: https://github.com/RVanDamme/PANKEGG/
  license_file: LICENSE
  summary: 'Parsing eggnog annotation file and quantitication file from trinity'
  description: |
    This script is part of the MAFIN pipeline and parse the annotations files from eggnog
    as well as the quantification of the RNA reads mapped to the transcript to output
    nice html result files
  dev_url: https://github.com/RVanDamme/PANKEGG/
  doc_source_url: https://github.com/RVanDamme/PANKEGG/blob/master/README.md
