{% set name = "PANKEGG" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RVanDamme/PANKEGG/archive/{{ version }}.tar.gz
  sha256: 264643d0e0b9cc8bff94db8f037f838f017dc99313f543ccc98918e531375d08

build:
  number: 0
  script: cp -r $SRC_DIR/PANKEGG $SP_DIR/PANKEGG;
    python $SRC_DIR/setup.py install --single-version-externally-managed --record=record.txt;
    ln -s $SP_DIR/PANKEGG/parser.py $PREFIX/bin/pankegg # [not win]
  # link: bin/pankegg

requirements:
  build:
    - python  3.8

  run:
    - python  3.8

test:
  imports:
    - PANKEGG

  commands:
    - pankegg -v > /dev/null
app:
  entry: pankegg

about:
  home: https://github.com/RVanDamme/PANKEGG/
  license_file: LICENSE
  summary: 'Parsing eggnog annotation file and quantitication file from trinity'
  description: |
    This script is part of the MAFIN pipeline and parse the annotations files from eggnog
    as well as the quantification of the RNA reads mapped to the transcript to output
    nice html result files
  dev_url: https://github.com/RVanDamme/PANKEGG/
  doc_source_url: https://github.com/RVanDamme/PANKEGG/blob/master/README.md
