{% set name = "PANKEGG" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/RVanDamme/PANKEGG/
  git_rev: 0.1.0
  git_depth: 1

build:
  number: 0
  script:
    - cp -r $SRC_DIR $SP_DIR/PANKEGG

requirements:
  build:
    - python  3.8

  run:
    - python  3.8

test:
  imports:
    - $SP_DIR/PANKEGG

  commands:
    - $SP_DIR/PANKEGG/parser.py -v > /dev/null
app:
  entry: $SP_DIR/PANKEGG/parser.py

about:
  home: https://github.com/RVanDamme/PANKEGG/
  license_file: LICENSE
  summary: 'Parsing eggnog annotation file and quantitication file from trinity'
  description: |
    This script is part of the MAFIN pipeline and parse the annotations files from eggnog
    as well as the quantification of the RNA reads mapped to the transcript to output
    nice html result files
  dev_url: https://github.com/RVanDamme/PANKEGG/
  doc_source_url: https://github.com/RVanDamme/PANKEGG/blob/master/README.md